version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

# Handlers match in order, put above the default handler.
handlers:

- url: /css
  static_dir: templates/css

- url: /js
  static_dir: templates/js

- url: /fonts
  static_dir: templates/fonts

- url: /images
  static_dir: templates/images

- url: /.*
  script: main.app
